spring.application.name=hollow-moon-server
#datasource.url=jdbc:mariadb://database.forestmoon/cellblock
datasource.url=jdbc:mariadb://192.168.0.44/cellblock
datasource.driver=org.mariadb.jdbc.Driver
datasource.username=cellblock
datasource.password=nimda
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.graphql.graphiql.enabled=true
server.port=5001
